/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * User login
     * @description Authenticates a user and returns a JWT token.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            username: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Authentication successful, returns JWT token. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              token?: string;
            };
          };
        };
        /** @description Invalid credentials. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a new log entry */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            agent_id: string;
            step_id: number;
            trace_id?: string;
            user_id?: string;
            /** Format: date-time */
            timestamp?: string;
            input_data: Record<string, never>;
            output: Record<string, never>;
            reasoning: string;
            /** @enum {string} */
            status?: 'success' | 'failure' | 'anomaly';
            reviewed?: boolean;
            review_comments?: string;
            metadata?: Record<string, never>;
            version?: number;
          };
        };
      };
      responses: {
        /** @description Log created successfully. */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/logs/{agent_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve logs for a specific agent */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Agent identifier. */
          agent_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A list of log entries. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/logs/{agent_id}/{step_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve detailed log entry */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Agent identifier. */
          agent_id: string;
          /** @description Step identifier. */
          step_id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Detailed log entry. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /**
     * Update log review status
     * @description Allows authorized users to mark a log entry as reviewed or update review comments. Only applicable for anomaly or pending review logs.
     */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Agent identifier. */
          agent_id: string;
          /** @description Step identifier. */
          step_id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            reviewed: boolean;
            review_comments?: string;
          };
        };
      };
      responses: {
        /** @description Log updated successfully. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Invalid update or log not found. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/logs/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search logs with filters */
    get: {
      parameters: {
        query?: {
          agent_id?: string;
          /** @description Filter by log status. */
          status?: string;
          trace_id?: string;
          from_date?: string;
          to_date?: string;
          /** @description Full-text search (MongoDB $text) over indexed log fields. */
          keyword?: string;
          /** @description When set, filter by manual review flag. */
          reviewed?: 'true' | 'false';
          page?: number;
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description A filtered list of log entries with pagination. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data?: Record<string, never>[];
              pagination?: {
                page?: number;
                limit?: number;
                total?: number;
                pages?: number;
              };
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/logs/summary/{agent_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get summary statistics for logs of an agent */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Agent identifier. */
          agent_id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Summary of logs including total count, anomalies, and review statuses. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
